# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../Templates/student_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class StudentItem(QtWidgets.QWidget):
    def __init__(self, parent, student):
        super().__init__(parent=parent)
        self.student = student
        self.setupUi(self)
        self.lbl_student_name.setText(self.student)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setFixedSize(500, 500)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_student_name = QtWidgets.QLabel(Form)
        self.lbl_student_name.setText("")
        self.lbl_student_name.setObjectName("lbl_student_name")
        self.verticalLayout.addWidget(self.lbl_student_name)
        self.lbl_student_screen = QtWidgets.QLabel(Form)
        self.lbl_student_screen.setText("")
        self.lbl_student_screen.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_student_screen.setObjectName("lbl_student_screen")
        self.verticalLayout.addWidget(self.lbl_student_screen)
        self.verticalLayout.setStretch(1, 1)

        QtCore.QMetaObject.connectSlotsByName(Form)
